version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "github-contribution-panel-string-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jwtt8mzogq1r"
s3_prefix = "github-contribution-panel-string-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "KeyAdministrator=\"ptramontina\""
image_repositories = []
