AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Github Contribution Panel String

  Function to write a string on the Github contribution panel, based on commits
  
Globals:
  Function:
    Timeout: 300 # 5 minutes. The amount of commits should be included on this time, otherwise, it will fail and retried.

Resources:
  GithubContributionPanelStringFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: github-contribution-panel-string/
      Handler: app.lambdaHandler
      Environment:
        Variables:
          GIT_USER: 'your-user'
          GIT_TOKEN: 'your-token'
          GIT_REPO: 'your-repo'
          GIT_BASE_URL: 'http://api.github.com'
          GIT_PATH: 'path/to/the/file.txt'
          STRING_TO_PRINT: 'sample'
          COMMIT_NUMBER: '5'
          INITIAL_DATE: 'First top/right date of the contribution panel'
      Runtime: nodejs14.x
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 14 * * ? *)

Outputs:
  GithubContributionPanelString:
    Description: "Function to write a string on the Github contribution panel, based on commits"
    Value: !GetAtt GithubContributionPanelStringFunction.Arn
